### ISSUE TITLE
Me want code

### ISSUE THREAD

**Issue by fragmuffin** [VRFamilyMan/CRTest#1]
@VRFamilyMan I believe in you dude :wink:

**Comment by VRFamilyMan** [comment]
I believe you have code.

**Comment by fragmuffin** [comment]
I do!
I haven't had a chance to contribute yet though.

First thing I'll look at are the uses of `subprocess`. I'll combine what I've learnt from previous projects. Hopefully I can help make it a bit more robust than what you described.
